language: node_js
node_js: stable
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  yarn: true
  directories:
    - node_modules

before_deploy:
  - "yarn workspace vue-insta-stories run build"
  - "yarn workspace example run build"

# Skip tests
script: 'true'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: packages/example/dist
  on:
    branch: main